Imports System.Data.SqlClient
Imports DevExpress.XtraGrid.Views.Base
Imports DevExpress.XtraGrid.Views.Grid
Imports Infragistics.Win
Imports Infragistics.Win.UltraWinGrid
Imports Syncfusion.Windows.Forms.Tools.ToggleButtonState
Imports Syncfusion.Windows.Forms.Tools
Imports System.Text.RegularExpressions

'Imports Syncfusion.Windows.Forms.Tools.ToggleButtonState

Public Class Frm_Employees_A
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        'SqlDataSource1.Fill()
        ' This line of code is generated by Data Source Configuration Wizard
        'EntityServerModeSource1.QueryableSource = New Retex.ERPEntities().Items
    End Sub
#Region " Declaration                                                                    "
    Dim vMasterBlock As String = "NI"
    Dim vSales_Employees_Auth_Checked_Changed = "N"
    Dim vcFrmLevel As New cFrmLevelVariables_A
    'Dim vcFrmLevel As Object = System.Reflection.Assembly.GetExecutingAssembly.CreateInstance(System.Reflection.Assembly.GetExecutingAssembly.GetName().Name & ".cFrmLevelVariables_" & vLang)
    Dim vSqlStatment(0) As String
    Dim vIsAdmin As String
    Dim vFocus As String = "Master"
    Dim vQuery As String = "N"
#End Region

#Region " Form Level                                                                     "
#Region " My Form                                                                        "
    Private Sub FRM_Users_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        'cControls.sLoadSettings(Me.Name, Grd_Summary)
        'sQuerySummary()
        'sQueryUser(vUsrCode)
        PictureBox1.SizeMode = PictureBoxSizeMode.StretchImage

        vMasterBlock = "NI"
        Txt_FndBy_IsActive.SelectedIndex = 0

        'Panel1.Font = New Font(fonts.Families(0), 12)
    End Sub
    Private Sub sFillSqlStatmentArray(ByVal pSqlstring As String)
        If vSqlStatment(UBound(vSqlStatment)) = "" Then
            vSqlStatment(UBound(vSqlStatment)) = pSqlstring
        Else
            ReDim Preserve vSqlStatment(UBound(vSqlStatment) + 1)
            vSqlStatment(UBound(vSqlStatment)) = pSqlstring
        End If
    End Sub
    Private Sub sEmptySqlStatmentArray()
        ReDim Preserve vSqlStatment(0)
        vSqlStatment(0) = ""
    End Sub
    Private Sub FRM_Users_Activated(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Activated
        vcFrmLevel.vParentFrm = Me.ParentForm
        sHide_ToolbarMain_Tools()

        sLoad_All_Statement()

        'Tab_Main.Tabs("Tab_Details").Selected = True

        If Tab_Main.Tabs("Tab_Summary").Selected = True Then
            vcFrmLevel.vParentFrm.sEnableTools(True, False, False, False, False, False, False, False, "", False, False, "التفاصيل")
        Else
            vcFrmLevel.vParentFrm.sEnableTools(True, True, True, True, True, True, True, True, "", True, False, "بحث")
        End If

        If vcFrmLevel.vRecPos > 0 Then
            vcFrmLevel.vParentFrm.sPrintRec(vcFrmLevel.vRecPos)
        Else
            vcFrmLevel.vParentFrm.sPrintRec("")
        End If

        'Dim vTool As Infragistics.Win.UltraWinToolbars.StateButtonTool
        'vTool = vcFrmLevel.vParentFrm.ToolBar_Main.Tools("Chk_Help")
        'sIsHelpEnabled(vTool.Checked)
    End Sub
    Private Sub FRM_Users_Closing(ByVal sender As Object, ByVal e As System.ComponentModel.CancelEventArgs) Handles Me.Closing
        If fSaveAll(True) = False Then
            e.Cancel = True
        Else
            e.Cancel = False
            vcFrmLevel.vParentFrm.sPrintRec("")
        End If

        cControls.sSaveSettings(Me.Name, Grd_Summary)
    End Sub
    Private Sub FRM_Users_Closed(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Closed
        If Me.ParentForm.MdiChildren.Length = 1 Then
            vcFrmLevel.vParentFrm.sEnableTools(True, True, True, True, True, True, True, False, "", True)
        End If
    End Sub
    Private Sub Txt_All_KeyUp(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) _
        Handles Txt_UserCode.KeyUp, Txt_Desc.KeyUp, Txt_DescL.KeyUp,
    Txt_Nationality.KeyUp, Txt_Gender.KeyUp, Txt_Id.KeyUp, Txt_Id_ExpiredDate.KeyUp,
    Txt_PassportNum.KeyUp, Txt_PassportNum_ExpiredDate.KeyUp, Txt_IPAN.KeyUp,
    Txt_FirstTimeDeal.KeyUp, Txt_BankCode.KeyUp, Txt_MTel.KeyUp, Txt_Email.KeyUp,
    Txt_Qualification.KeyUp, Txt_MaritalStatus.KeyUp, Txt_ContractType.KeyUp,
    Txt_ContractStartDate.KeyUp, Txt_ContractEndDate.KeyUp, Txt_Salary.KeyUp,
    Txt_HomeAllowance.KeyUp, Txt_Title.KeyUp, Txt_Department.KeyUp,
    Txt_HealthExpiredDate.KeyUp, Txt_BirthDate.KeyUp, Txt_address.KeyUp,
    Txt_Remarks.KeyUp, Chk_IsActive.KeyUp

        If e.KeyData = Keys.Enter Then
            SendKeys.Send("{Tab}")
        End If

    End Sub
    Private Sub Txt_All_ValueChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) _
    Handles Txt_UserCode.ValueChanged, Txt_Desc.ValueChanged, Txt_DescL.ValueChanged,
    Txt_Nationality.ValueChanged, Txt_Gender.ValueChanged, Txt_Id.ValueChanged, Txt_Id_ExpiredDate.ValueChanged,
    Txt_PassportNum.ValueChanged, Txt_PassportNum_ExpiredDate.ValueChanged, Txt_IPAN.ValueChanged,
    Txt_FirstTimeDeal.ValueChanged, Txt_BankCode.ValueChanged, Txt_MTel.ValueChanged, Txt_Email.ValueChanged,
    Txt_Qualification.ValueChanged, Txt_MaritalStatus.ValueChanged, Txt_ContractType.ValueChanged,
    Txt_ContractStartDate.ValueChanged, Txt_ContractEndDate.ValueChanged, Txt_Salary.ValueChanged,
    Txt_HomeAllowance.ValueChanged, Txt_Title.ValueChanged, Txt_Department.ValueChanged,
    Txt_HealthExpiredDate.ValueChanged, Txt_BirthDate.ValueChanged, Txt_address.ValueChanged,
    Txt_Remarks.ValueChanged, Chk_IsActive.CheckedChanged, Txt_HR_Systems.ValueChanged

        If vMasterBlock = "NI" Then
            vMasterBlock = "I"
        ElseIf vMasterBlock = "N" Then
            vMasterBlock = "U"
        End If

        If sender.Name = "Chk_IsActive" Then
            If Chk_IsActive.Checked Then
                Chk_IsActive.Tag = "Y"
                Chk_IsActive.Text = "يعمل"
            Else
                Chk_IsActive.Tag = "N"
                Chk_IsActive.Text = "لا يعمل"
            End If
        End If

        If sender.Name = "Txt_Nationality" Or sender.name = "Txt_Salary" Then
            If Txt_Nationality.Text = "" Then
                Exit Sub
            End If

            If vQuery = "Y" Then
                Exit Sub
            End If

            Dim vInsurance As String = cControls.fReturnValue(" Select Insurance From Nationality " &
                                                              " Where Code = " & Txt_Nationality.Value &
                                                              " And Company_Code = " & vCompanyCode, Me.Name)

            If vInsurance <> "" Then
                Txt_Insurance.Text = vInsurance * fIsNull(Txt_Salary.Value, 0) / 100
            Else
                Txt_Insurance.Text = ""
            End If
        End If
    End Sub

    Private Sub Chk_AllToggle_ToggleStateChanged(sender As Object, e As Syncfusion.Windows.Forms.Tools.ToggleStateChangedEventArgs) _
        Handles Chk_IsSupervisor.ToggleStateChanged

        If sender.ToggleState = Active Then
            sender.Tag = True
        Else
            sender.Tag = False
        End If

        If vMasterBlock = "NI" Then
            vMasterBlock = "I"
        ElseIf vMasterBlock = "N" Then
            vMasterBlock = "U"
        End If
    End Sub
    Private Sub CHK_IsSuperVisor_CheckedChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) _
        Handles Chk_StopDeal.CheckedChanged, Chk_IsSalesMan.CheckedChanged

        If vMasterBlock = "NI" Then
            vMasterBlock = "I"
        ElseIf vMasterBlock = "N" Then
            vMasterBlock = "U"
        End If

        If sender.Checked Then
            sender.Tag = "Y"
        Else
            sender.Tag = "N"
        End If
    End Sub
#End Region
#Region " DataBase                                                                       "
#Region " Save                                                                           "
    Private Function fIfsaveNeeded() As Boolean
        If vMasterBlock = "I" Or vMasterBlock = "U" Then
            Return True
        End If

        Dim vRow As UltraGridRow

        Return False
    End Function
    Public Function fSaveAll(ByVal pAskMe As Boolean) As Boolean
        If vcFrmLevel.vParentFrm.ToolBar_Main.Tools("Btn_Save").SharedProps.Enabled = False Then
            Return True
        End If

        If fIfsaveNeeded() = False Then
            Return True
        End If

        sEmptySqlStatmentArray()

        If pAskMe Then
            If vcFrmLevel.vParentFrm.sForwardMessage("6", Me) = MsgBoxResult.Yes Then
                If fSaveValidation() Then
                    sSaveMain()
                    sSave_MainPicture()
                Else
                    Return False
                End If

                'If fValidate_Departments() Then
                '    sSave_Departments()
                'Else
                '    Return False
                'End If
            Else
                vMasterBlock = "NI"
                Return True
            End If
        Else
            If fSaveValidation() = True Then
                sSaveMain()
                sSave_MainPicture()
            Else
                Return False
            End If

            'If fValidate_Departments() Then
            '    sSave_Departments()
            'Else
            '    Return False
            'End If
        End If

        Dim vRowCounter As Integer = cControls.fSendData(vSqlStatment, Me.Name)
        If vRowCounter > 0 Then
            vMasterBlock = "N"
            Txt_Code.Text = Txt_UserCode.Text

            vcFrmLevel.vParentFrm.sForwardMessage("7", Me)
            Return True
        End If
    End Function
#End Region
#Region " Query                                                                          "
    Public Sub sQuery(Optional ByVal pRecPos As Integer = Nothing, Optional ByVal pItemCode As String = Nothing, Optional ByVal pIsGoTo As Boolean = False)
        If fSaveAll(True) = False Then
            Return
        End If

        Dim vFetchRec As Integer
        If pItemCode = Nothing Then
            If pIsGoTo = False Then
                If pRecPos = Nothing Then
                    vFetchRec = 1
                Else
                    vFetchRec = vcFrmLevel.vRecPos + pRecPos
                    If vFetchRec > cControls.fCount_Rec(" From  Employees " &
                                                        " Where 1 = 1     " &
                                                        " And Company_Code = " & vCompanyCode) Then

                        vcFrmLevel.vParentFrm.sForwardMessage("33", Me)
                        Return
                    End If
                    If vFetchRec = 0 Then
                        vcFrmLevel.vParentFrm.sForwardMessage("34", Me)
                        vFetchRec = 1
                    End If

                End If
            End If
        End If

        vQuery = "Y"

        If pRecPos = -2 Then
            vFetchRec = cControls.fCount_Rec(" From Employees " &
                                             " Where 1 = 1     " &
                                             " And   Company_Code = " & vCompanyCode)
        End If

        Dim vFetchCondition As String
        If pItemCode = Nothing Then
            vFetchCondition = " And RecPos = '" & vFetchRec & "' "
                    Else
            vFetchCondition = " And Code = '" & Trim(pItemCode) & "' "
        End If

        Try

            Dim vSQlcommand As New SqlCommand
            vSQlcommand.CommandText =
            " With MyEmployees as (      " & vbCrLf &
            " Select Code,               " & vbCrLf &
            "       DescA,               " & vbCrLf &
            "       DescL,               " & vbCrLf &
            "       Nationality_Code as Nationality,    " & vbCrLf &
            "       Gender,              " & vbCrLf &
            "       ID,                  " & vbCrLf &
            "       ID_ExpiredDate,      " & vbCrLf &
            "       PassPort_Num,        " & vbCrLf &
            "       PassPort_Num_ExpiredDate,  " & vbCrLf &
            "       IPAN,                " & vbCrLf &
            "       BankCode_Code,       " & vbCrLf &
            "       MTel,                " & vbCrLf &
            "       Email,               " & vbCrLf &
            "       Qualification,       " & vbCrLf &
            "       Marital_Status,      " & vbCrLf &
            "       ContractType_Code,   " & vbCrLf &
            "       Contract_StartDate,  " & vbCrLf &
            "       Contract_EndDate,    " & vbCrLf &
            "       Salary,              " & vbCrLf &
            "       Home_Allowance,      " & vbCrLf &
            "       Title,               " & vbCrLf &
            "       Department_Code,     " & vbCrLf &
            "       HealthExpiredDate,   " & vbCrLf &
            "       BirthDate,           " & vbCrLf &
            "       Address,             " & vbCrLf &
            "       Remarks,             " & vbCrLf &
            "       Branch_Code,         " & vbCrLf &
            "       FirstTimeDeal,       " & vbCrLf &
            "       IsActive,            " & vbCrLf &
            "       Insurance,           " & vbCrLf &
            "       HR_System_Code,      " & vbCrLf &
            "       Employees.Picture,   " & vbCrLf &
            "       ROW_Number() Over (Order By Code) RecPos, " & vbCrLf &
            "       Is_Supervisor          " & vbCrLf &
            "                              " & vbCrLf &
            "        From Employees        " & vbCrLf &
            "        Where 1 = 1           " & vbCrLf &
            "        And Company_Code =    " & vCompanyCode & " ) " &
            "                              " &
            "        Select * From MyEmployees  " & vbCrLf &
            "        Where 1 = 1 " &
            vFetchCondition

            vSQlcommand.Connection = cControls.vSqlConn
            cControls.vSqlConn.Open()
            Dim vSqlReader As SqlDataReader = vSQlcommand.ExecuteReader
            Do While vSqlReader.Read

                If IsDBNull(vSqlReader("RecPos")) = False Then
                    vcFrmLevel.vRecPos = Trim(vSqlReader("RecPos"))
                End If
                vcFrmLevel.vParentFrm.sPrintRec(vSqlReader("RecPos"))

                'Code
                Txt_UserCode.Text = Trim(vSqlReader("Code"))
                Txt_Code.Text = Trim(vSqlReader("Code"))

                'DescA 
                If IsDBNull(vSqlReader("DescA")) = False Then
                    Txt_Desc.Text = Trim(vSqlReader("DescA"))
                Else
                    Txt_Desc.Text = ""
                End If

                'DescL 
                If IsDBNull(vSqlReader("DescL")) = False Then
                    Txt_DescL.Text = Trim(vSqlReader("DescL"))
                Else
                    Txt_DescL.Text = ""
                End If

                'Nationality
                If IsDBNull(vSqlReader("Nationality")) = False Then
                    Txt_Nationality.Value = Trim(vSqlReader("Nationality"))
                Else
                    Txt_Nationality.SelectedIndex = -1
                End If

                'Gender
                If IsDBNull(vSqlReader("Gender")) = False Then
                    Txt_Gender.Value = Trim(vSqlReader("Gender"))
                Else
                    Txt_Gender.SelectedIndex = -1
                End If

                'ID
                If IsDBNull(vSqlReader("ID")) = False Then
                    Txt_Id.Text = Trim(vSqlReader("ID"))
                Else
                    Txt_Id.Text = ""
                End If

                'ID Expired Date
                If IsDBNull(vSqlReader("ID_ExpiredDate")) = False Then
                    Txt_Id_ExpiredDate.Text = Trim(vSqlReader("ID_ExpiredDate"))
                Else
                    Txt_Id_ExpiredDate.Text = Nothing
                End If

                'PassPort
                If IsDBNull(vSqlReader("PassPort_Num")) = False Then
                    Txt_PassportNum.Text = Trim(vSqlReader("PassPort_Num"))
                Else
                    Txt_PassportNum.Text = ""
                End If

                'PassPort ExpiredDate
                If IsDBNull(vSqlReader("PassPort_Num_ExpiredDate")) = False Then
                    Txt_PassportNum_ExpiredDate.Text = Trim(vSqlReader("PassPort_Num_ExpiredDate"))
                Else
                    Txt_PassportNum_ExpiredDate.Text = Nothing
                End If

                'IPAN
                If IsDBNull(vSqlReader("IPAN")) = False Then
                    Txt_IPAN.Text = Trim(vSqlReader("IPAN"))
                Else
                    Txt_IPAN.Text = ""
                End If

                'Gender
                If IsDBNull(vSqlReader("BankCode_Code")) = False Then
                    Txt_BankCode.Value = Trim(vSqlReader("BankCode_Code"))
                Else
                    Txt_BankCode.SelectedIndex = -1
                End If

                'MTel
                If IsDBNull(vSqlReader("MTel")) = False Then
                    Txt_MTel.Text = Trim(vSqlReader("MTel"))
                Else
                    Txt_MTel.Text = ""
                End If

                'Email1
                If IsDBNull(vSqlReader("Email")) = False Then
                    Txt_Email.Text = Trim(vSqlReader("Email"))
                Else
                    Txt_Email.Text = ""
                End If

                'Qualification
                If IsDBNull(vSqlReader("Qualification")) = False Then
                    Txt_Qualification.Text = Trim(vSqlReader("Qualification"))
                Else
                    Txt_Qualification.Text = ""
                End If

                'Marital Status
                If IsDBNull(vSqlReader("Marital_Status")) = False Then
                    Txt_MaritalStatus.Value = Trim(vSqlReader("Marital_Status"))
                Else
                    Txt_MaritalStatus.SelectedIndex = -1
                End If

                'ContractType Code
                If IsDBNull(vSqlReader("ContractType_Code")) = False Then
                    Txt_ContractType.Value = Trim(vSqlReader("ContractType_Code"))
                Else
                    Txt_ContractType.SelectedIndex = -1
                End If

                'Contract Start Date
                If IsDBNull(vSqlReader("Contract_StartDate")) = False Then
                    Txt_ContractStartDate.Text = Trim(vSqlReader("Contract_StartDate"))
                Else
                    Txt_ContractStartDate.Text = Nothing
                End If

                'Contract End Date
                If IsDBNull(vSqlReader("Contract_EndDate")) = False Then
                    Txt_ContractEndDate.Text = Trim(vSqlReader("Contract_EndDate"))
                Else
                    Txt_ContractEndDate.Text = Nothing
                End If

                'Salary
                If IsDBNull(vSqlReader("Salary")) = False Then
                    Txt_Salary.Value = vSqlReader("Salary")
                Else
                    Txt_Salary.Value = Nothing
                End If

                'Home_Allowance
                If IsDBNull(vSqlReader("Home_Allowance")) = False Then
                    Txt_HomeAllowance.Value = vSqlReader("Home_Allowance")
                Else
                    Txt_HomeAllowance.Value = Nothing
                End If

                'Title
                If IsDBNull(vSqlReader("Title")) = False Then
                    Txt_Title.Text = Trim(vSqlReader("Title"))
                Else
                    Txt_Title.Text = ""
                End If

                'Department Code
                If IsDBNull(vSqlReader("Department_Code")) = False Then
                    Txt_Department.Value = vSqlReader("Department_Code")
                Else
                    Txt_Department.SelectedIndex = -1
                End If

                'HealthExpiredDate
                If IsDBNull(vSqlReader("HealthExpiredDate")) = False Then
                    Txt_HealthExpiredDate.Text = Trim(vSqlReader("HealthExpiredDate"))
                Else
                    Txt_HealthExpiredDate.Text = Nothing
                End If

                'HealthExpiredDate
                If IsDBNull(vSqlReader("BirthDate")) = False Then
                    Txt_BirthDate.Text = Trim(vSqlReader("BirthDate"))
                Else
                    Txt_BirthDate.Text = Nothing
                End If

                'Address
                If IsDBNull(vSqlReader("Address")) = False Then
                    Txt_address.Text = Trim(vSqlReader("Address"))
                Else
                    Txt_address.Text = ""
                End If

                'Remarks
                If IsDBNull(vSqlReader("Remarks")) = False Then
                    Txt_Remarks.Text = Trim(vSqlReader("Remarks"))
                Else
                    Txt_Remarks.Text = ""
                End If

                'Branch_Code
                If IsDBNull(vSqlReader("Branch_Code")) = False Then
                    Txt_Branch.Value = vSqlReader("Branch_Code")
                Else
                    Txt_Branch.SelectedIndex = -1
                End If

                'First Time Deal
                If IsDBNull(vSqlReader("FirstTimeDeal")) = False Then
                    Txt_FirstTimeDeal.Text = Trim(vSqlReader("FirstTimeDeal"))
                Else
                    Txt_FirstTimeDeal.Text = Nothing
                End If

                'IsActive
                If IsDBNull(vSqlReader("IsActive")) = False Then
                    If vSqlReader("IsActive") = "N" Then
                        Chk_IsActive.Checked = False
                    Else
                        Chk_IsActive.Checked = True
                    End If
                End If

                'Insurance
                If IsDBNull(vSqlReader("Insurance")) = False Then
                    Txt_Insurance.Text = Trim(vSqlReader("Insurance"))
                Else
                    Txt_Insurance.Text = ""
                End If

                'HR_System
                If IsDBNull(vSqlReader("Hr_System_Code")) = False Then
                    Txt_HR_Systems.Value = vSqlReader("Hr_System_Code")
                Else
                    Txt_HR_Systems.SelectedIndex = -1
                End If

                'Is_Supervisor
                If IsDBNull(vSqlReader("Is_Supervisor")) = False Then
                    If vSqlReader("Is_Supervisor") Then
                        Chk_IsSupervisor.ToggleState = ToggleButtonState.Active
                    Else
                        Chk_IsSupervisor.ToggleState = ToggleButtonState.Inactive
                    End If
                End If

                'Picture
                If IsDBNull(vSqlReader("Picture")) = False Then
                    Dim arrayImage() As Byte = CType(vSqlReader("Picture"), Byte())
                    Dim ms As New IO.MemoryStream(arrayImage)
                    PictureBox1.Image = Image.FromStream(ms)
                Else
                    PictureBox1.Image = Nothing
                End If
            Loop

            cControls.vSqlConn.Close()
            vSqlReader.Close()

            'Txt_UserCode.ReadOnly = True

            vQuery = "N"

            'sQuery_Departments()

        Catch ex As Exception
            cControls.vSqlConn.Close()
            MessageBox.Show(ex.Message)
            'cException.sHandleException(ex.Message, Me.Name, "sQuery")
        End Try
        vMasterBlock = "N"
    End Sub

    Private Sub sLoad_All_Statement()
        Try
            Dim vSqlString As String
            vSqlString = " Select Branches.Code,        " &
                         "        Branches.DescA        " &
                         " From   Branches              " &
                         "                              " &
                         " Where  1 = 1                 " &
                         " And    Company_Code = " & vCompanyCode &
                         "                              " &
                         " Select Code, Desc" & vLang &
                         " From Nationality " &
                         "                  " &
                         " Where  1 = 1                 " &
                         " And    Company_Code = " & vCompanyCode &
                         "                              " &
                         " Select Code, Desc" & vLang & " From Contract_Types " &
                         " Where  1 = 1                 " &
                         " And    Company_Code = " & vCompanyCode &
                         "                                      " &
                         " Select Code, Desc" & vLang & " From Departments " &
                         " Where  1 = 1                 " &
                         " And    Company_Code = " & vCompanyCode &
                         " Select Code, Desc" & vLang &
                         " From   BankCodes " &
                         "                              " &
                         " Where  1 = 1                 " &
                         " And    Company_Code = " & vCompanyCode &
                         " Select Code, Desc" & vLang & " From HR_Systems " &
                         " Where  1 = 1                 " &
                         " And    Company_Code = " & vCompanyCode

            Dim vsqlCommand As New SqlClient.SqlCommand
            vsqlCommand.CommandText = vSqlString

            vsqlCommand.Connection = cControls.vSqlConn
            cControls.vSqlConn.Open()
            Dim vSqlReader As SqlClient.SqlDataReader = vsqlCommand.ExecuteReader

            Txt_Branch.Items.Clear()
            Do While vSqlReader.Read
                Txt_Branch.Items.Add(Trim(vSqlReader(0)), Trim(vSqlReader(1)))
            Loop

            vSqlReader.NextResult()

            Txt_Nationality.Items.Clear()
            Do While vSqlReader.Read
                Txt_Nationality.Items.Add(vSqlReader(0), vSqlReader(1))
            Loop

            vSqlReader.NextResult()

            Txt_ContractType.Items.Clear()
            Do While vSqlReader.Read
                Txt_ContractType.Items.Add(vSqlReader(0), vSqlReader(1))
            Loop

            vSqlReader.NextResult()

            Txt_Department.Items.Clear()
            Do While vSqlReader.Read
                Txt_Department.Items.Add(vSqlReader(0), vSqlReader(1))
            Loop

            vSqlReader.NextResult()

            Txt_BankCode.Items.Clear()
            Do While vSqlReader.Read
                Txt_BankCode.Items.Add(vSqlReader(0), vSqlReader(1))
            Loop

            vSqlReader.NextResult()

            Txt_HR_Systems.Items.Clear()
            Do While vSqlReader.Read
                Txt_HR_Systems.Items.Add(vSqlReader(0), vSqlReader(1))
            Loop

            vSqlReader.Close()
        Catch ex As Exception
            MessageBox.Show("Error loading data: " & ex.Message, "Load Error", MessageBoxButtons.OK, MessageBoxIcon.Error)
        Finally
            If cControls.vSqlConn.State = ConnectionState.Open Then
                cControls.vSqlConn.Close()
            End If
        End Try
    End Sub

#End Region
#Region " Delete                                                                         "
    Public Sub sDelete()
        If vMasterBlock = "I" Then
            sNewRecord()
        ElseIf vMasterBlock = "N" Or vMasterBlock = "U" Then
            If vcFrmLevel.vParentFrm.sForwardMessage("39", Me) = MsgBoxResult.Yes Then
                Dim vSqlstring As String
                vSqlstring = " Delete From Employees " &
                             " Where  Code = '" & Txt_UserCode.Text & "' " &
                             " And    Company_Code = " & vCompanyCode

                If cControls.fSendData(vSqlstring, Me.Name) > 0 Then
                    vcFrmLevel.vParentFrm.sForwardMessage("38", Me)
                    sNewRecord()
                End If
            End If
        End If
    End Sub
#End Region
#Region " Find                                                                           "

#End Region
#End Region
#Region " New Record                                                                     "
    Public Sub sNewRecord()
        Try
            If fSaveAll(True) = False Then
                Return
            End If

            Tab_Main.Tabs("Tab_Details").Selected = True

            Txt_UserCode.Clear()
            Txt_Desc.Clear()
            Txt_DescL.Clear()
            Txt_Nationality.Clear()
            Txt_Gender.Clear()
            Txt_Id.Clear()
            Txt_Id_ExpiredDate.Value = Nothing
            Txt_PassportNum.Clear()
            Txt_PassportNum_ExpiredDate.Value = Nothing
            Txt_IPAN.Clear()
            Txt_FirstTimeDeal.Value = Nothing
            Txt_BankCode.SelectedIndex = -1
            Txt_MTel.Clear()
            Txt_Email.Clear()
            Txt_Qualification.Clear()
            Txt_MaritalStatus.SelectedIndex = -1
            Txt_ContractType.SelectedIndex = -1
            Txt_ContractStartDate.Value = Nothing
            Txt_ContractEndDate.Value = Nothing
            Txt_Salary.Value = Nothing
            Txt_HomeAllowance.Value = Nothing
            Txt_Title.Clear()
            Txt_Department.SelectedIndex = -1
            Txt_HealthExpiredDate.Value = Nothing
            Txt_BirthDate.Value = Nothing
            Txt_address.Clear()
            Txt_Remarks.Clear()
            Txt_Insurance.Clear()
            Txt_HR_Systems.SelectedIndex = -1

            Txt_UserCode.Select()

            PictureBox1.Image = Nothing

            Txt_UserCode.ReadOnly = False

            Chk_IsActive.Checked = True
            Chk_IsSupervisor.ToggleState = ToggleButtonState.Inactive

            vMasterBlock = "NI"
            vcFrmLevel.vRecPos = 0
            vcFrmLevel.vParentFrm.sPrintRec("")

        Catch ex As Exception
            MessageBox.Show(ex.Message)
        End Try
    End Sub
    Private Sub sNewCode()
        Dim vSqlCommand As String
        vSqlCommand = " Select IsNull(Max(Code), 0) + 1 From Employees " &
                      " Where 1 = 1        " &
                      " And Company_Code = " & vCompanyCode

        Txt_UserCode.Text = cControls.fReturnValue(vSqlCommand, Me.Name)
    End Sub
    Private Sub sClear_EmployeeType()
        Opt_E.Checked = True
        Opt_C.Checked = False
        Opt_S.Checked = False
    End Sub

#End Region
#Region " sOpenLov                                                                       "
    Private Sub sOpenLov(ByVal pSqlStatment As String, ByVal pTitle As String)
        vLovReturn1 = ""
        VLovReturn2 = ""
        Dim Frm_Lov As New FRM_LovGeneral_A(pSqlStatment, pTitle)
        Frm_Lov.ShowDialog()
        If vLovReturn1.Length > 0 And VLovReturn2.Length > 0 Then
            sQuery(pItemCode:=vLovReturn1)
        End If
    End Sub
#End Region
#Region " Tab Mangment                                                                   "
    Private Sub Tab_Main_SelectedTabChanging(ByVal sender As Object, ByVal e As Infragistics.Win.UltraWinTabControl.SelectedTabChangingEventArgs) Handles Tab_Main.SelectedTabChanging
        If Tab_Main.Tabs("Tab_Details").Selected = True Then
            If fSaveAll(True) = False Then
                e.Cancel = True
            Else
                e.Cancel = False
                sNewRecord()
            End If
        End If
    End Sub
    Private Sub Tab_Main_SelectedTabChanged(ByVal sender As System.Object, ByVal e As Infragistics.Win.UltraWinTabControl.SelectedTabChangedEventArgs) Handles Tab_Main.SelectedTabChanged
        If Tab_Main.Tabs("Tab_Summary").Selected = True Then
            vcFrmLevel.vParentFrm = Me.ParentForm
            vcFrmLevel.vParentFrm.sEnableTools(True, False, False, False, False, False, False, False, "", False, False, "التفاصيل")
            sQuerySummary()
            Txt_Back.Visible = False
        ElseIf Tab_Main.Tabs("Tab_Details").Selected = True Then
            vcFrmLevel.vParentFrm.sEnableTools(True, True, True, True, True, True, True, True, "", False, False, "بحث")
            Txt_Back.Visible = True

            'If Grd_Summary.Selected.Rows.Count > 0 Then
            '    sQuery(pItemCode:=Grd_Summary.ActiveRow.Cells("Code").Value)
            'Else
            '    sNewRecord()
            'End If
        End If
    End Sub
    Public Sub sChangeTab()
        If Tab_Main.Tabs("Tab_Summary").Selected Then
            Tab_Main.Tabs("Tab_Details").Selected = True
            vcFrmLevel.vParentFrm.sEnableTools(True, True, True, True, True, True, True, True, "", True, False, "بحث")
        Else
            Tab_Main.Tabs("Tab_Summary").Selected = True
            vcFrmLevel.vParentFrm.sEnableTools(True, False, False, False, False, False, False, False, "", False, False, "التفاصيل")
        End If
    End Sub
#End Region
#Region " Help                                                                           "
    Public Sub sIsHelpEnabled(ByVal pEnabled As Boolean)
        'UltraToolTipManager1.Enabled = pEnabled
    End Sub
#End Region
#End Region
#Region " Master                                                                         "
#Region " Save                                                                           "
    Private Function fSaveValidation() As Boolean
        If Txt_UserCode.Text = "" Then
            vcFrmLevel.vParentFrm.sForwardMessage("3", Me)
            Txt_UserCode.Select()
            Return False
        End If

        If vMasterBlock = "I" Then
            If cControls.fIsExist(" From  Employees    " &
                                  " Where Code         = '" & Txt_UserCode.Text & "' " &
                                  " And   Company_Code =  " & vCompanyCode, Me.Name) Then

                vcFrmLevel.vParentFrm.sForwardMessage("12", Me)
                Txt_UserCode.Select()
                Txt_UserCode.SelectAll()
                Return False
            End If
        ElseIf vMasterBlock = "U" Then
            'If cControls.fIsExist(" From  Employees            " &
            '                  " Where 1 = 1 " &
            '                  " And Code <> '" & Trim(Txt_Code.Text) & "' " &
            '                  " And   Company_Code = " & vCompanyCode, Me.Name) Then

            '    vcFrmLevel.vParentFrm.sForwardMessage("12", Me)
            '    Txt_Code.Select()
            '    Return False
            'End If
        End If

        If Txt_Desc.Text.Length = 0 And Txt_DescL.Text.Length = 0 Then
            vcFrmLevel.vParentFrm.sForwardMessage("4", Me)
            Txt_Desc.Select()
            Return False
        End If

        If cControls.fCount_Rec(" From Employees Where DescA = '" & Trim(Txt_Desc.Text) & "'" &
                                " And Code <> '" & Trim(Txt_Code.Text) & "'" &
                                " And Company_Code = " & vCompanyCode) > 0 Then
            vcFrmLevel.vParentFrm.sForwardMessage("82", Me)
            Txt_Desc.Select()
            Return False
        End If

        If Txt_FirstTimeDeal.Value Is Nothing Then
            vcFrmLevel.vParentFrm.sForwardMessage("53", Me)
            Txt_FirstTimeDeal.Select()
            Return False
        End If

        If Txt_Id.Text.Length > 0 Then
            If Txt_Id.Text.Length > 10 Or Txt_Id.Text.Length < 10 Then
                ErrorProvider1.SetError(Txt_Id, "خطأ في الادخال")
                Txt_Id.Select()
                Return False
            Else
                ErrorProvider1.SetError(Txt_Id, "")
            End If
        Else
            ErrorProvider1.SetError(Txt_Id, "")
        End If

        If Txt_MTel.Text.Length > 0 Then
            If Txt_MTel.Text.Length > 10 Or Txt_MTel.Text.Length < 10 Then
                ErrorProvider1.SetError(Txt_MTel, "خطأ في الادخال")
                Txt_MTel.Select()
                Return False
            Else
                ErrorProvider1.SetError(Txt_MTel, "")
            End If
        Else
            ErrorProvider1.SetError(Txt_MTel, "")
        End If

        If Txt_IPAN.Text.Length > 0 Then
            If Txt_IPAN.Text.Length > 24 Or Txt_IPAN.Text.Length < 24 Then
                ErrorProvider1.SetError(Txt_IPAN, "خطأ في الادخال")
                Txt_IPAN.Select()
                Return False
            Else
                ErrorProvider1.SetError(Txt_IPAN, "")
            End If
        Else
            ErrorProvider1.SetError(Txt_IPAN, "")
        End If


        If Txt_Nationality.SelectedIndex = -1 Then
            vcFrmLevel.vParentFrm.sForwardMessage("158", Me)
            Txt_Nationality.Select()
            Return False
        End If

        If Txt_Gender.SelectedIndex = -1 Then
            vcFrmLevel.vParentFrm.sForwardMessage("159", Me)
            Txt_Gender.Select()
            Return False
        End If

        If Txt_Qualification.Text = "" Then
            vcFrmLevel.vParentFrm.sForwardMessage("160", Me)
            Txt_Qualification.Select()
            Return False
        End If

        If Txt_MaritalStatus.SelectedIndex = -1 Then
            vcFrmLevel.vParentFrm.sForwardMessage("161", Me)
            Txt_MaritalStatus.Select()
            Return False
        End If

        If Txt_ContractType.SelectedIndex = -1 Then
            vcFrmLevel.vParentFrm.sForwardMessage("162", Me)
            Txt_ContractType.Select()
            Return False
        End If

        If Txt_ContractStartDate.Value Is Nothing Then
            vcFrmLevel.vParentFrm.sForwardMessage("163", Me)
            Txt_ContractStartDate.Select()
            Return False
        End If

        If Txt_Salary.Value Is Nothing Then
            vcFrmLevel.vParentFrm.sForwardMessage("164", Me)
            Txt_Salary.Select()
            Return False
        End If

        If Txt_Title.Text = "" Then
            vcFrmLevel.vParentFrm.sForwardMessage("165", Me)
            Txt_Title.Select()
            Return False
        End If

        If Txt_Department.SelectedIndex = -1 Then
            vcFrmLevel.vParentFrm.sForwardMessage("166", Me)
            Txt_Department.Select()
            Return False
        End If

        If Txt_BirthDate.Value Is Nothing Then
            vcFrmLevel.vParentFrm.sForwardMessage("167", Me)
            Txt_BirthDate.Select()
            Return False
        End If

        If Trim(Txt_Email.Text) <> "" Then
            If Not Regex.IsMatch(Trim(Txt_Email.Text), "\A(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z", RegexOptions.IgnoreCase) Then
                vcFrmLevel.vParentFrm.sForwardMessage("168", Me)
                Txt_Email.Select()
                Return False
            End If
        End If

        If Txt_HR_Systems.SelectedIndex = -1 Then
            vcFrmLevel.vParentFrm.sForwardMessage("175", Me)
            Txt_HR_Systems.Select()
            Return False
        End If

        Return True
    End Function
    Private Sub sSaveMain()
        Try
            Dim vId_ExpiredDate, vPassPort_ExpiredDate, vContractStartDate, vContractEndDate, vHealthExpiredDate, vFirstTimeDeal,
            vBranch, vHome_Allowence, vBankCode As String

            Dim vSqlCommand As String = ""

            If Not Txt_Id_ExpiredDate.Value = Nothing Then
                vId_ExpiredDate = " '" & Strings.Format(Txt_Id_ExpiredDate.Value, "MM-dd-yyyy") & "' "
            Else
                vId_ExpiredDate = "NULL"
            End If

            If Not Txt_PassportNum_ExpiredDate.Value = Nothing Then
                vPassPort_ExpiredDate = " '" & Strings.Format(Txt_PassportNum_ExpiredDate.Value, "MM-dd-yyyy") & "' "
            Else
                vPassPort_ExpiredDate = "NULL"
            End If

            If Not Txt_ContractStartDate.Value = Nothing Then
                vContractStartDate = " '" & Strings.Format(Txt_ContractStartDate.Value, "MM-dd-yyyy") & "' "
            Else
                vContractStartDate = "NULL"
            End If

            If Not Txt_ContractEndDate.Value = Nothing Then
                vContractEndDate = " '" & Strings.Format(Txt_ContractEndDate.Value, "MM-dd-yyyy") & "' "
            Else
                vContractEndDate = "NULL"
            End If

            If Txt_BankCode.SelectedIndex = -1 Then
                vBankCode = "NULL"
            Else
                vBankCode = " '" & Txt_BankCode.Value & "' "
            End If

            If Txt_HomeAllowance.Value Is Nothing Then
                vHome_Allowence = "NULL"
            Else
                vHome_Allowence = Txt_HomeAllowance.Value
            End If

            If Not Txt_HealthExpiredDate.Value = Nothing Then
                vHealthExpiredDate = " '" & Strings.Format(Txt_HealthExpiredDate.Value, "MM-dd-yyyy") & "' "
            Else
                vHealthExpiredDate = "NULL"
            End If

            If Not Txt_FirstTimeDeal.Value = Nothing Then
                vFirstTimeDeal = " '" & Strings.Format(Txt_FirstTimeDeal.Value, "MM-dd-yyyy") & "' "
            Else
                vFirstTimeDeal = "NULL"
            End If

            If Txt_Branch.Value = Nothing Then
                vBranch = "NULL"
            Else
                vBranch = " '" & Txt_Branch.Value & "' "
            End If

            If vMasterBlock = "I" Then

                vSqlCommand = " Insert Into Employees     (             Code,                  Company_Code,                  DescA,                         DescL,                   Nationality_Code,                Gender,                          Id,                 Id_ExpiredDate,                   PassPort_Num,             Passport_Num_ExpiredDate,              IPAN,                FirstTimeDeal,       BankCode_Code,                  MTel,                          Email,                          Qualification,                     Marital_Status,               ContractType_Code,             Contract_StartDate,         Contract_EndDate,            Salary,                Home_Allowance,                 Title,                      Department_Code,           HealthExpiredDate,                             BirthDate,                                         Address,                         Remarks,                 Branch_Code,         IsActive,                          Insurance,                             Hr_System_Code,                    Is_Supervisor ) " &
                            "                  Values     ('" & Trim(Txt_UserCode.Text) & "', " & vCompanyCode & ", '" & Trim(Txt_Desc.Text) & "', '" & Trim(Txt_DescL.Text) & "', " & Txt_Nationality.Value & ", '" & Txt_Gender.Value & "', '" & Trim(Txt_Id.Text) & "', " & vId_ExpiredDate & ", '" & Trim(Txt_PassportNum.Text) & "', " & vPassPort_ExpiredDate & ", '" & Txt_IPAN.Text & "', " & vFirstTimeDeal & ", " & vBankCode & ", '" & Trim(Txt_MTel.Text) & "', '" & Trim(Txt_Email.Text) & "', '" & Trim(Txt_Qualification.Text) & "', '" & Txt_MaritalStatus.Value & "', " & Txt_ContractType.Value & ", " & vContractStartDate & ", " & vContractEndDate & ", " & Txt_Salary.Value & ", " & vHome_Allowence & ", '" & Trim(Txt_Title.Text) & "', " & Txt_Department.Value & ", " & vHealthExpiredDate & ", '" & Strings.Format(Txt_BirthDate.Value, "MM-dd-yyyy") & "', '" & Trim(Txt_address.Text) & "', '" & Trim(Txt_Remarks.Text) & "',  " & vBranch & ", '" & Chk_IsActive.Tag & "', " & fIsNull(Txt_Insurance.Value, "NULL") & ", " & Txt_HR_Systems.Value & ", '" & Chk_IsSupervisor.Tag & "' )"

                sFillSqlStatmentArray(vSqlCommand)

            ElseIf vMasterBlock = "U" Then
                vSqlCommand = " Update   Employees          " & vbCrLf &
                              " Set   Code               =  " & Trim(Txt_UserCode.Text) & ", " & vbCrLf &
                              "       DescA              = '" & Trim(Txt_Desc.Text) & "', " & vbCrLf &
                              "       DescL              = '" & Trim(Txt_DescL.Text) & "', " & vbCrLf &
                              "       Nationality_Code   =  " & Txt_Nationality.Value & ", " & vbCrLf &
                              "       Gender             = '" & Txt_Gender.Value & "', " & vbCrLf &
                              "       ID                 = '" & Trim(Txt_Id.Text) & "', " & vbCrLf &
                              "       ID_ExpiredDate     =  " & vId_ExpiredDate & ", " & vbCrLf &
                              "       PassPort_Num       = '" & Trim(Txt_PassportNum.Text) & "', " & vbCrLf &
                              "       PassPort_Num_ExpiredDate = " & vPassPort_ExpiredDate & ", " & vbCrLf &
                              "       IPAN               = '" & Trim(Txt_IPAN.Text) & "', " & vbCrLf &
                              "       FirstTimeDeal      =  " & vFirstTimeDeal & ", " &
                              "       BankCode_Code      =  " & vBankCode & ", " & vbCrLf &
                              "       MTel               = '" & Trim(Txt_MTel.Text) & "', " & vbCrLf &
                              "       Email              = '" & Trim(Txt_Email.Text) & "', " & vbCrLf &
                              "       Qualification      = '" & Trim(Txt_Qualification.Text) & "', " & vbCrLf &
                              "       Marital_Status     = '" & Trim(Txt_MaritalStatus.Value) & "', " & vbCrLf &
                              "       ContractType_Code  =  " & Trim(Txt_ContractType.Value) & ", " & vbCrLf &
                              "       Contract_StartDate =  " & vContractStartDate & ", " & vbCrLf &
                              "       Contract_EndDate   =  " & vContractEndDate & ", " & vbCrLf &
                              "       Salary             =  " & Txt_Salary.Value & ", " & vbCrLf &
                              "       Home_Allowance     =  " & vHome_Allowence & ", " & vbCrLf &
                              "       Title              = '" & Trim(Txt_Title.Text) & "', " & vbCrLf &
                              "       Department_Code    =  " & Txt_Department.Value & ", " & vbCrLf &
                              "       HealthExpiredDate  =  " & vHealthExpiredDate & ", " & vbCrLf &
                              "       BirthDate          = '" & Strings.Format(Txt_BirthDate.Value, "MM-dd-yyyy") & "', " & vbCrLf &
                              "       Address            = '" & Trim(Txt_address.Text) & "', " & vbCrLf &
                              "       Remarks            = '" & Trim(Txt_Remarks.Text) & "', " & vbCrLf &
                              "       Branch_Code        =  " & vBranch & ", " & vbCrLf & vbCrLf &
                              "       IsActive           = '" & Chk_IsActive.Tag & "', " & vbCrLf &
                              "       Insurance          =  " & fIsNull(Txt_Insurance.Value, "NULL") & vbCrLf & ", " &
                              "       HR_System_Code     =  " & Txt_HR_Systems.Value & ", " &
                              "       Is_Supervisor      = '" & Chk_IsSupervisor.Tag & "' " &
                              "                             " & vbCrLf &
                              " Where Code               =  " & Trim(Txt_Code.Text) &
                              " And   Company_Code       =  " & vCompanyCode

                sFillSqlStatmentArray(vSqlCommand)
            End If
        Catch ex As Exception
            MessageBox.Show(ex.Message)
        End Try
    End Sub
    Private Function sSave_MainPicture()
        Try
            If Not IsDBNull(PictureBox1.Image) Then
                If Not PictureBox1.Image Is Nothing Then
                    Dim vSqlString As String
                    Dim ms As New System.IO.MemoryStream
                    Dim arrPicture() As Byte

                    vSqlString = " Update Employees Set Picture = (@image) " &
                                 " Where  Code = '" & Trim(Txt_UserCode.Text) & "' " &
                                 " And    Company_Code = " & vCompanyCode

                    Dim vMyCommand As New SqlCommand(vSqlString, cControls.vSqlConn)

                    PictureBox1.Image.Save(ms, System.Drawing.Imaging.ImageFormat.Jpeg)
                    'If ms.Length > MAX_IMAGE_SIZE Then
                    '    MsgBox("image trop grosse")
                    'End If
                    arrPicture = ms.GetBuffer()
                    ms.Flush()
                    vMyCommand.Parameters.Add("@image", SqlDbType.Image).Value = arrPicture

                    cControls.vSqlConn.Open()
                    vMyCommand.ExecuteNonQuery()
                    cControls.vSqlConn.Close()
                End If
            End If
        Catch ex As Exception
            MessageBox.Show(ex.Message)
            cControls.vSqlConn.Close()
        End Try
    End Function

#End Region
#End Region
#Region " Details                                                                        "
#Region " Departments                                                                    "
#Region " DataBase                                                                       "
#Region " Query                                                                          "

#End Region
#Region " Save                                                                           "
    Private Function fValidate_Departments() As Boolean
        Try
            Return True
        Catch ex As Exception
            MessageBox.Show(ex.Message)
        End Try

    End Function

#End Region
#End Region
#Region " Form Level                                                                     "

    Private Sub Grd_Departments_Enter(ByVal sender As Object, ByVal e As System.EventArgs)
        Try
            vFocus = "Departments"
        Catch ex As Exception
            MessageBox.Show(ex.Message)
        End Try
    End Sub
#End Region
#End Region
#End Region

#Region " Summary                                                                        "
    Private Sub sQuerySummary(Optional ByVal pCode As String = "", Optional ByVal pDesc As String = "")
        Try
            Dim vCodeFilter, vDescFilter As String

            If pCode = "" Then
                vCodeFilter = ""
            Else
                vCodeFilter = " And Employees.Code Like '%" & pCode & "%'"
            End If

            If pDesc = "" Then
                vDescFilter = ""
            Else
                vDescFilter = " And Employees.DescA Like '%" & pDesc & "%'"
            End If

            Dim vsqlCommand As New SqlClient.SqlCommand
            Dim vRowCounter As Integer
            vsqlCommand.CommandText =
            "  Select Employees.Code,                      " &
            "         Employees.DescA,                     " &
            "         IsActive                             " &
            "                                              " &
            " From Employees                               " &
            "                                              " &
            " Where 1 = 1                                  " &
            " And Company_Code = " & vCompanyCode

            vsqlCommand.Connection = cControls.vSqlConn
            cControls.vSqlConn.Open()
            Dim vSqlReader As SqlClient.SqlDataReader = vsqlCommand.ExecuteReader
            vRowCounter = 0
            Dim vRow As UltraGridRow
            DTS_Summary.Rows.Clear()

            Do While vSqlReader.Read
                DTS_Summary.Rows.SetCount(vRowCounter + 1)
                DTS_Summary.Rows(vRowCounter)("Code") = Trim(vSqlReader(0))

                If vSqlReader.IsDBNull(1) = False Then
                    DTS_Summary.Rows(vRowCounter)("DescA") = Trim(vSqlReader(1))
                End If

                vRow = Grd_Summary.Rows(vRowCounter)

                If vSqlReader.IsDBNull(2) = False Then
                    If vSqlReader(2) = "Y" Then
                        DTS_Summary.Rows(vRowCounter)("Status") = "يعمل"
                    Else
                        DTS_Summary.Rows(vRowCounter)("Status") = "لا يعمل"
                        vRow.Appearance.BackColor = Color.LightBlue
                    End If
                Else
                    DTS_Summary.Rows(vRowCounter)("Status") = "لا يعمل"
                    vRow.Appearance.BackColor = Color.LightBlue
                End If

                vRowCounter += 1
            Loop
            cControls.vSqlConn.Close()
            vSqlReader.Close()
            Grd_Summary.UpdateData()

        Catch ex As Exception
            cControls.vSqlConn.Close()
            MessageBox.Show(ex.Message)
            'cException.sHandleException(ex.Message, Me.Name, "sQuerySummaryMain")
        End Try
    End Sub

    Private Sub Txt_AllFilters_ValueChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) _
    Handles Txt_FndByCode.ValueChanged, Txt_FndByDesc.ValueChanged, Txt_FndBy_IsActive.ValueChanged

        sQuerySummary(Trim(Txt_FndByCode.Text), Trim(Txt_FndByDesc.Text))
    End Sub

    Private Sub Grd_Summary_DoubleClick(ByVal sender As Object, ByVal e As System.EventArgs) Handles Grd_Summary.DoubleClick

        If Grd_Summary.Selected.Rows.Count > 0 Then
            sQuery(pItemCode:=Grd_Summary.ActiveRow.Cells("Code").Value)
        Else
            sNewRecord()
        End If

        Tab_Main.Tabs("Tab_Details").Selected = True
    End Sub

    Private Sub GridControl1_DoubleClick(sender As Object, e As EventArgs) Handles GridControl1.DoubleClick
        Dim view As DevExpress.XtraGrid.Views.Layout.LayoutView = GridControl1.MainView

        Dim vCode As String = Trim(view.GetRowCellValue(view.FocusedRowHandle, "Code"))

        sQuery(pItemCode:=vCode)
        Tab_Main.Tabs("Tab_Details").Selected = True

    End Sub

    Private Sub Chk_SelectAll_CheckedChanged(sender As Object, e As EventArgs) Handles Chk_SelectAll.CheckedChanged
        Dim vItem As ValueListItem

        If Chk_SelectAll.Checked Then
            For Each vItem In Txt_SalesInvoice_Employees_Auth.Items
                vItem.CheckState = CheckState.Checked
            Next
        ElseIf Not Chk_SelectAll.Checked Then
            For Each vItem In Txt_SalesInvoice_Employees_Auth.Items
                vItem.CheckState = CheckState.Unchecked
            Next
        End If

    End Sub

#End Region
    Private Sub sHide_ToolbarMain_Tools()
        vcFrmLevel.vParentFrm.ToolBar_Main.Tools("Btn_New").SharedProps.Visible = True
        vcFrmLevel.vParentFrm.ToolBar_Main.Tools("Btn_Save").SharedProps.Visible = True
        vcFrmLevel.vParentFrm.ToolBar_Main.Tools("Btn_Delete").SharedProps.Visible = True
        vcFrmLevel.vParentFrm.ToolBar_Main.Tools("Btn_Print").SharedProps.Visible = True
        vcFrmLevel.vParentFrm.ToolBar_Main.Tools("Btn_NextRecord").SharedProps.Visible = True
        vcFrmLevel.vParentFrm.ToolBar_Main.Tools("Btn_PreviousRecord").SharedProps.Visible = True
        vcFrmLevel.vParentFrm.ToolBar_Main.Tools("Btn_LastRecord").SharedProps.Visible = True
        vcFrmLevel.vParentFrm.ToolBar_Main.Tools("Btn_FirstRecord").SharedProps.Visible = True
        vcFrmLevel.vParentFrm.ToolBar_Main.Tools("Btn_CloseWindow").SharedProps.Visible = True
        vcFrmLevel.vParentFrm.ToolBar_Main.Tools("Btn_GotoRecord").SharedProps.Visible = True
        vcFrmLevel.vParentFrm.ToolBar_Main.Tools("Btn_ChangeUser").SharedProps.Visible = True
        vcFrmLevel.vParentFrm.ToolBar_Main.Tools("Themes").SharedProps.Visible = True
    End Sub

    Private Sub Txt_Back_Click(sender As Object, e As EventArgs) Handles Txt_Back.Click
        Tab_Main.Tabs("Tab_Summary").Selected = True
    End Sub

    Private Sub Btn_Close_Click(sender As Object, e As EventArgs) Handles Btn_Close.Click
        Me.Close()
    End Sub

    Private Sub Btn_SelectPicture_Click(sender As Object, e As EventArgs) Handles Btn_SelectPicture.Click
        Try
            If vMasterBlock = "NI" Then
                Return
            End If

            If vMasterBlock = "I" Then
                If fSaveAll(False) = False Then
                    Return
                End If
            End If

            OpenFileDialog1.Filter = "JPEGS|*.jpg|GIFS|*.gif|Bitmaps|*.bmp|all files|*.*"
            OpenFileDialog1.FileName = ""
            OpenFileDialog1.ShowDialog()
            If Not OpenFileDialog1.FileName = "" Then
                PictureBox1.Image = Image.FromFile(OpenFileDialog1.FileName)
                'PictureBox1.SizeMode = PictureBoxSizeMode.CenterImage
                'cControls.sSaveImage(Image.FromFile(OpenFileDialog1.FileName), "Company")
                sSave_MainPicture()
            End If

        Catch ex As Exception
            MessageBox.Show(ex.Message)
        End Try
    End Sub

End Class